Support non-trivial lambdas in Scala-style rendering format
zio/izumi-reflect pull request #490
Opened 2024-11-08 22:01 UTC by varshith257

2024-11-08 22:04 UTC, varshith257 commented
@pshirshov I have this approach in my mind to support nontrivial lamdas but it still emitting the same. Any suggestions for it?

2024-11-08 22:43 UTC, pshirshov requested changes
This is good, thank you! But I think it should be done on Ref level

2024-11-08 23:53 UTC, pshirshov commented
```
 [error] /home/runner/work/izumi-reflect/izumi-reflect/izumi-reflect/izumi-reflect/src/main/scala/izumi/reflect/macrortti/LightTypeTag.scala:285:6: illegal start of simple expression
[error] =    case LightTypeTagRef.FullReference(_, args, _) if args.nonEmpty =>
```

I guess it might be a good idea to build locally first. `sbt +clean +test:compile +test`

2024-11-09 22:03 UTC, varshith257 commented
Ok, I will move these changes to LightTypeTag.scala

2024-11-11 17:12 UTC, pshirshov commented
@varshith257 : could you tell me if you still wish to complete this? May I help you somehow?

2024-11-11 17:16 UTC, varshith257 commented
@pshirshov Yeah! I will push to complete it by EOD and will reachout you if I get struck anywhere

2024-11-11 17:18 UTC, varshith257 commented
Just I needed to push the changes to ref and I exported there but a minor fixes needed of there for accessing shortname etc..as they are throwing few compilation errors

2025-11-23 01:20 UTC, closed without merging